language: objective-c
osx_image: xcode7.1

env:
  global:
  - PROJECT=KGNAutoLayout
  - SCHEME=$PROJECT
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4s"
    - DESTINATION="OS=8.2,name=iPhone 5"
    - DESTINATION="OS=8.3,name=iPhone 5s"
    - DESTINATION="OS=8.4,name=iPhone 6"

    - DESTINATION="OS=9.0,name=iPhone 4s"
    - DESTINATION="OS=9.0,name=iPhone 5"
    - DESTINATION="OS=9.0,name=iPhone 5s"
    - DESTINATION="OS=9.0,name=iPhone 6"
    - DESTINATION="OS=9.0,name=iPhone 6 Plus"
    - DESTINATION="OS=9.0,name=iPhone 6s"
    - DESTINATION="OS=9.0,name=iPhone 6s Plus"

    - DESTINATION="OS=9.1,name=iPhone 6s"
    - DESTINATION="OS=9.1,name=iPhone 6s Plus"    

script: 
  - xcodebuild clean test -project "$PROJECT.xcodeproj" -scheme "$SCHEME" -sdk iphonesimulator -destination "$DESTINATION"
